installCRDs: true

replicaCount: 1

image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent
  # tag: latest

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  capabilities:
    drop:
    - ALL

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534

serviceAccount:
  create: true
  annotations: {}
  name: ""

webhook:
  create: true
  certCheckInterval: "5m"
  certDir: /tmp/k8s-webhook-server/serving-certs
  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

certController:
  create: true
  requeueInterval: "5m"
  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

metrics:
  listen:
    port: 8080

logLevel: info

concurrent: 1
