controller:
  config:
    use-forwarded-headers: "true"
  metrics:
    enabled: true
  nodeSelector:
    kubernetes.io/hostname: kind-control-plane
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  ingressClassResource:
    default: true
  admissionWebhooks:
    enabled: false
  service:
    type: NodePort
    ports:
      http: 80
      https: 443
    nodePorts:
      http: 30080
      https: 30443
    targetPorts:
      http: http
      https: https
