FROM golang:1.23-alpine AS build
WORKDIR /app
COPY main.go ./
RUN go mod init backend && go mod tidy && go build -o backend main.go

FROM alpine:3.16
WORKDIR /app
COPY --from=build /app/backend ./backend
COPY wait-for-it.sh ./wait-for-it.sh
EXPOSE 8000
CMD ["./backend"]
