apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: seccamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
      - name: backend
        image: harbor.seccamp.com/seccamp2025/seccamp-backend:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "seccamp2025"
      imagePullSecrets:
      - name: harbor-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: seccamp-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: seccamp-app
rules:
  - apiGroups: [""] 
    resources: ["pods"]
    verbs: ["create", "list", "get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: seccamp-app
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: seccamp-app
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
